//
//  DetailsBeerInteractor.swift
//  iBeer
//
//  Created by Jefferson Martins de Sá on 20/01/2019.
//  Copyright (c) 2019 Jefferson Martins de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBeerBusinessLogic {
  func getBeer(request: DetailsBeer.GetBeer.Request)
}

class DetailsBeerInteractor: DetailsBeerBusinessLogic {
    var presenter: DetailsBeerPresentationLogic?
    var worker: BeersWorker?
    
    // MARK: requests
    
    func getBeer(request: DetailsBeer.GetBeer.Request) {
        worker = BeersWorker()
        worker?.getBeer(request: request, completionSuccess: { (response) in
            let response =  DetailsBeer.GetBeer.Response(beer: response)
            self.presenter?.presentDetailsBeer(response: response)
        }, completionFailure: { (error) in
            self.presenter?.presentErrorMessage(error: error)
        })
    }
}
